# Generated by Django 4.1.7 on 2024-08-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True, max_length=255, null=True, verbose_name="نام کاربری"
            ),
        ),
    ]
