# Generated by Django 4.1.7 on 2024-09-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True,
                default="username",
                max_length=255,
                verbose_name="نام کاربری",
            ),
        ),
    ]
