# Generated by Django 4.1.7 on 2024-10-12 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rating", "0002_rename_ratings_rating_rating_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="rating",
            name="value",
            field=models.IntegerField(
                choices=[
                    (1, "poor"),
                    (2, "fair"),
                    (3, "good"),
                    (4, "very good"),
                    (5, "excellent"),
                ],
                default=0,
                help_text="1=Poor, 2=Fair, 3=Good, 4=Very Good, 5=Excellent",
                verbose_name="rating value",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "value")},
        ),
        migrations.RemoveField(
            model_name="rating",
            name="rating",
        ),
    ]
