# Generated by Django 4.1.7 on 2024-08-23 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phonenumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=15, region=None, unique=True
                    ),
                ),
                (
                    "about_me",
                    models.TextField(default="یادداشت کنید", verbose_name="درباره من"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "مرد"), ("F", "خانم")],
                        default="M",
                        max_length=30,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=50, verbose_name="کشور"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="تهران", max_length=50, verbose_name="شهر"
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        default="/profile_photo",
                        upload_to="",
                        verbose_name="عکس پروفایل",
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True, related_name="following", to="profiles.profile"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="پروفایل",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
