# Generated by Django 4.1.7 on 2024-09-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phonenumber",
            field=models.CharField(max_length=15),
        ),
    ]
