# Generated by Django 4.1.7 on 2024-09-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="twitter_handle",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="twitter_handle"
            ),
        ),
    ]
