# Generated by Django 4.1.7 on 2024-09-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_profile_twitter_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="profiles.profile"
            ),
        ),
    ]
